### PR TITLE
Switch from Rinkeby to Goerli

### PR DESCRIPTION
**Pull request by aquiladev**
We discussed to remove Rinkeby from UNS config, that is why I prep the draft PR.
Goerli testnet connected to Mumbai testnet, that is second reason why we need to switch to Goerli

Things to do:
- re-generate docs from templates
- update asset rinkeby-faucet-free-ether.png
- some contracts are not present on Goerli (eg TwitterValidationOperator deprecated), we need to make sure that there is remark for that

### CODE REVIEW

**Review by cpengilly — APPROVED** [review]
looks good. Thank you for helping with this!

**Review by cpengilly — APPROVED** [review]
Thanks!

**Comment by DancingAxolotl** [comment]
@aquiladev Nice changes! Thanks for updating the docs.

It looks like you still have to generate the docs pages for new contracts.
You can run 
```
yarn && yarn render:cns-contracts && yarn render:uns-contracts

```
This will pull the uns-config.json file, generate tables with up to date contracts and update the docs files. Otherwise the changes will not be reflected on the docs pages.

**Review by DancingAxolotl — APPROVED** [review]
Looks good!

**Comment by aquiladev** [comment]
@DancingAxolotl @cpengilly pls merge

**Pull request merged**
